/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "MailBox.h"

bool_t
xdr_message_t (XDR *xdrs, message_t objp)
{
	register int32_t *buf;

	 if (!xdr_vector (xdrs, (char *)objp, 80,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messageWithCode_t (XDR *xdrs, messageWithCode_t *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->status))
		 return FALSE;
	 if (!xdr_message_t (xdrs, objp->message))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_user_t (XDR *xdrs, user_t *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->id))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->name, 20,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messageInsArgs_t (XDR *xdrs, messageInsArgs_t *objp)
{
	register int32_t *buf;

	 if (!xdr_user_t (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->messageNumber))
		 return FALSE;
	 if (!xdr_message_t (xdrs, objp->message))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messageRetArgs_t (XDR *xdrs, messageRetArgs_t *objp)
{
	register int32_t *buf;

	 if (!xdr_user_t (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->messageNumber))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messageListRet_t (XDR *xdrs, messageListRet_t *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_int (xdrs, &objp->messageCount))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->messages, 20,
			sizeof (message_t), (xdrproc_t) xdr_message_t))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 20 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->messageNumbers, 20,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->messageNumbers;
					i < 20; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_int (xdrs, &objp->messageCount))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->messages, 20,
			sizeof (message_t), (xdrproc_t) xdr_message_t))
			 return FALSE;
		buf = XDR_INLINE (xdrs, ( 20 ) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_vector (xdrs, (char *)objp->messageNumbers, 20,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			{
				register int *genp;

				for (i = 0, genp = objp->messageNumbers;
					i < 20; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->messageCount))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->messages, 20,
		sizeof (message_t), (xdrproc_t) xdr_message_t))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->messageNumbers, 20,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_messageDelArgs_t (XDR *xdrs, messageDelArgs_t *objp)
{
	register int32_t *buf;

	 if (!xdr_user_t (xdrs, &objp->user))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->messageNumber))
		 return FALSE;
	return TRUE;
}
