/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAILBOX_H_RPCGEN
#define _MAILBOX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char message_t[80];

struct messageWithCode_t {
	int status;
	message_t message;
};
typedef struct messageWithCode_t messageWithCode_t;

struct user_t {
	int id;
	char name[20];
};
typedef struct user_t user_t;

struct messageInsArgs_t {
	user_t user;
	int messageNumber;
	message_t message;
};
typedef struct messageInsArgs_t messageInsArgs_t;

struct messageRetArgs_t {
	user_t user;
	int messageNumber;
};
typedef struct messageRetArgs_t messageRetArgs_t;

struct messageListRet_t {
	int messageCount;
	message_t messages[20];
	int messageNumbers[20];
};
typedef struct messageListRet_t messageListRet_t;

struct messageDelArgs_t {
	user_t user;
	int messageNumber;
};
typedef struct messageDelArgs_t messageDelArgs_t;

#define MAIL_BOX_PRG 0xFF1277
#define MAIL_BOX_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define START 1
extern  int * start_1(user_t *, CLIENT *);
extern  int * start_1_svc(user_t *, struct svc_req *);
#define quit 2
extern  int * quit_1(user_t *, CLIENT *);
extern  int * quit_1_svc(user_t *, struct svc_req *);
#define INSERT_MESSAGE 3
extern  int * insert_message_1(messageInsArgs_t *, CLIENT *);
extern  int * insert_message_1_svc(messageInsArgs_t *, struct svc_req *);
#define RETRIEVE_MESSAGE 4
extern  messageWithCode_t * retrieve_message_1(messageRetArgs_t *, CLIENT *);
extern  messageWithCode_t * retrieve_message_1_svc(messageRetArgs_t *, struct svc_req *);
#define LIST_ALL_MESSAGES 5
extern  messageListRet_t * list_all_messages_1(user_t *, CLIENT *);
extern  messageListRet_t * list_all_messages_1_svc(user_t *, struct svc_req *);
#define DELETE_MESSAGE 6
extern  int * delete_message_1(messageDelArgs_t *, CLIENT *);
extern  int * delete_message_1_svc(messageDelArgs_t *, struct svc_req *);
extern int mail_box_prg_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define START 1
extern  int * start_1();
extern  int * start_1_svc();
#define quit 2
extern  int * quit_1();
extern  int * quit_1_svc();
#define INSERT_MESSAGE 3
extern  int * insert_message_1();
extern  int * insert_message_1_svc();
#define RETRIEVE_MESSAGE 4
extern  messageWithCode_t * retrieve_message_1();
extern  messageWithCode_t * retrieve_message_1_svc();
#define LIST_ALL_MESSAGES 5
extern  messageListRet_t * list_all_messages_1();
extern  messageListRet_t * list_all_messages_1_svc();
#define DELETE_MESSAGE 6
extern  int * delete_message_1();
extern  int * delete_message_1_svc();
extern int mail_box_prg_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message_t (XDR *, message_t);
extern  bool_t xdr_messageWithCode_t (XDR *, messageWithCode_t*);
extern  bool_t xdr_user_t (XDR *, user_t*);
extern  bool_t xdr_messageInsArgs_t (XDR *, messageInsArgs_t*);
extern  bool_t xdr_messageRetArgs_t (XDR *, messageRetArgs_t*);
extern  bool_t xdr_messageListRet_t (XDR *, messageListRet_t*);
extern  bool_t xdr_messageDelArgs_t (XDR *, messageDelArgs_t*);

#else /* K&R C */
extern bool_t xdr_message_t ();
extern bool_t xdr_messageWithCode_t ();
extern bool_t xdr_user_t ();
extern bool_t xdr_messageInsArgs_t ();
extern bool_t xdr_messageRetArgs_t ();
extern bool_t xdr_messageListRet_t ();
extern bool_t xdr_messageDelArgs_t ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAILBOX_H_RPCGEN */
